# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      id:   setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: set msbuild path env var
      shell: bash
      run: |
        export VCTargetsPath="${{ steps.setup-msbuild.outputs.msbuildPath }}../../Microsoft/VC/v170"
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      # Tests are disabled until I filter them to only run ones that don't need packages
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
